; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26129.0 

	TITLE	D:\git_repository\cpp_template_edu\template_Lazy_Instantiation\template_Lazy_Instantiation\template_Lazy_Instantiation.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Odtp
; File d:\git_repository\cpp_template_edu\template_lazy_instantiation\template_lazy_instantiation\template_lazy_instantiation.cpp
_TEXT	SEGMENT
_main	PROC

	push	ebp
	mov	ebp, esp

	xor	eax, eax

	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
