; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26129.0 

	TITLE	D:\git_repository\cpp_template_edu\template1\template1\template1.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
PUBLIC	??$square@H@@YAHH@Z				; square<int>
PUBLIC	?foo@?$Test@H@@QAEXXZ				; Test<int>::foo
; Function compile flags: /Odtp
; File d:\git_repository\cpp_template_edu\template1\template1\template1.cpp
;	COMDAT ?foo@?$Test@H@@QAEXXZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?foo@?$Test@H@@QAEXXZ PROC				; Test<int>::foo, COMDAT
; _this$ = ecx

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	esp, ebp
	pop	ebp
	ret	0
?foo@?$Test@H@@QAEXXZ ENDP				; Test<int>::foo
_TEXT	ENDS
; Function compile flags: /Odtp
; File d:\git_repository\cpp_template_edu\template1\template1\template1.cpp
;	COMDAT ??$square@H@@YAHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
??$square@H@@YAHH@Z PROC				; square<int>, COMDAT

	push	ebp
	mov	ebp, esp

	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _a$[ebp]

	pop	ebp
	ret	0
??$square@H@@YAHH@Z ENDP				; square<int>
_TEXT	ENDS
; Function compile flags: /Odtp
; File d:\git_repository\cpp_template_edu\template1\template1\template1.cpp
_TEXT	SEGMENT
_t1$ = -12						; size = 4
_n2$ = -8						; size = 4
_n1$ = -4						; size = 4
_main	PROC

	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH

	push	3
	call	??$square@H@@YAHH@Z			; square<int>
	add	esp, 4
	mov	DWORD PTR _n1$[ebp], eax

	push	3
	call	??$square@H@@YAHH@Z			; square<int>
	add	esp, 4
	mov	DWORD PTR _n2$[ebp], eax

	lea	ecx, DWORD PTR _t1$[ebp]
	call	?foo@?$Test@H@@QAEXXZ			; Test<int>::foo

	xor	eax, eax

	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
